// <auto-generated />
namespace MVCEF6.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test67 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test67));
        
        string IMigrationMetadata.Id
        {
            get { return "201510021035033_test67"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
